//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GogWishlist {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GogWishlist.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gog wishlist viewer.
        /// </summary>
        public static string app_title {
            get {
                return ResourceManager.GetString("app_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string button_ok {
            get {
                return ResourceManager.GetString("button_ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to show only discounted.
        /// </summary>
        public static string checkbox_discounted {
            get {
                return ResourceManager.GetString("checkbox_discounted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no page address.
        /// </summary>
        public static string error_page_address {
            get {
                return ResourceManager.GetString("error_page_address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to response not contains wishlist data cache.
        /// </summary>
        public static string error_response_cache_not_found {
            get {
                return ResourceManager.GetString("error_response_cache_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to response is empty.
        /// </summary>
        public static string error_response_empty {
            get {
                return ResourceManager.GetString("error_response_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Need to set username first.
        /// </summary>
        public static string error_username {
            get {
                return ResourceManager.GetString("error_username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wishlist data error.
        /// </summary>
        public static string error_wishlist_data {
            get {
                return ResourceManager.GetString("error_wishlist_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wishlist has no products.
        /// </summary>
        public static string error_wishlist_products_not_found {
            get {
                return ResourceManager.GetString("error_wishlist_products_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to discount percent descend.
        /// </summary>
        public static string sort_discount {
            get {
                return ResourceManager.GetString("sort_discount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to price ascend.
        /// </summary>
        public static string sort_price {
            get {
                return ResourceManager.GetString("sort_price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string username {
            get {
                return ResourceManager.GetString("username", resourceCulture);
            }
        }
    }
}
